classdef FrameType < redux.Component
	properties
		buttons % A structure of radio buttons
	end
	
	methods
		function this = FrameType(parent)
			p = redux.InputParser;
			p.addParent();
			parse(p, parent);
			
% 			this.handle = vt.Component.Layout.HButtonBox( ...
% 				p.Results.parent, ...
% 				'Padding', 5, ...
% 				'HorizontalAlignment', 'left' ...
% 			);
% % 			'ButtonSize', [200 20], ... 
		
			this.buttons(1) = uicontrol( ...
				'Parent', p.Results.parent.handle, ...
				'Style', 'radiobutton', ...
				'String', 'frame', ...
				'Value', 1 ...
			); 
			this.buttons(2) = uicontrol( ...
				'Parent', p.Results.parent.handle, ...
				'Style', 'radiobutton', ...
				'String', 'mean', ...
				'Value', 0 ...
			); 
			this.buttons(3) = uicontrol( ...
				'Parent', p.Results.parent.handle, ...
				'Style', 'radiobutton', ...
				'String', 'std dev', ... 
				'Value', 0 ...
			);
		
			% This is a little sketchy...
			this.handle = this.buttons;
		end
	end
	
end

