classdef FrameType < vt.Component & vt.Action.Dispatcher & vt.State.Listener
	properties
		buttons % A structure of radio buttons
		actionType = @vt.Action.SetFrameType
	end
	
	methods
		function this = FrameType(parent)
			p = vt.InputParser;
			p.addParent();
			parse(p, parent);
			
			this.handle = vt.Component.Layout.HButtonBox( ...
				p.Results.parent, ...
				'Padding', 5, ...
				'HorizontalAlignment', 'left' ...
			);
% 			'ButtonSize', [200 20], ... 
		
			this.buttons(1) = uicontrol( ...
				'Parent', this.handle.handle, ...
				'Style', 'radiobutton', ...
				'String', 'frame', ...
				'Value', 1, ...
				'Callback', {@(source, event) onClicked(this, source, event)} ...
			); 
			this.buttons(2) = uicontrol( ...
				'Parent', this.handle.handle, ...
				'Style', 'radiobutton', ...
				'String', 'mean', ...
				'Value', 0, ...
				'Callback', {@(source, event) onClicked(this, source, event)} ...
			); 
			this.buttons(3) = uicontrol( ...
				'Parent', this.handle.handle, ...
				'Style', 'radiobutton', ...
				'String', 'std dev', ... 
				'Value', 0, ...
				'Callback', {@(source, event) onClicked(this, source, event)} ...
			);
		end

		% http://www.mathworks.com/matlabcentral/fileexchange/47982-gui-layout-toolbox
		% 18 September 2016
		function onClicked( this, source, ~ ) 
			set( this.buttons(this.buttons==source), 'Value', 1 ); % select this
			set( this.buttons(this.buttons~=source), 'Value', 0 ) % unselect others
			
			buttonString = get( source, 'String' );
			this.action.dispatch(buttonString);
		end
		
		function [] = onVideoChange(this, ~)
			set( this.buttons, 'Enable', 'on' );
		end
	end
	
end

