classdef Gui < vt.Root & vt.State.Listener
	properties
		state
		styles
		reducer
		gui
		actionListener
		
		% TODO: get this from user-specified preferences
		currentRegion = struct('shape', 'Circle')
	end
	
	methods
		function this = Gui()
			this.log = vt.Log(2);
			this.log.on();
		end
		
		function [] = run(this)
			this.state = vt.State();
			this.reducer = vt.Reducer(this.state);
			this.actionListener = vt.Action.Listener(this.reducer);
			
			this.styles = this.createStyles();
			this.gui = this.createInterface();
			
			this.initializeListeners();
			
			set(findall(this.gui.Window.handle, 'Type', 'uicontrol'), 'Enable', 'off');
		end
		
		function [] = initializeListeners(this)
			% Initialize all the gui elements with a log, register their state
			% listeners, and get them registered with the action listener
			fields = fieldnames(this.gui);
			for iField = 1:numel(fields)
				obj = this.gui.(fields{iField});
				if(isa(obj, 'vt.Root'))
					obj.log = this.log;
				end
				if(isa(obj, 'vt.State.Listener'))
					obj.registerAllMethodsToState(this.state);
				end
				if(isa(obj, 'vt.Action.Dispatcher'))
					this.actionListener.registerAction(obj.action);
				end
			end
			
			% Give all the properties of this vt.Gui a log as well
			propertyList = properties(this);
			for iProp = 1:numel(properties(this))
				prop = propertyList{iProp};
				if(isa(this.(prop), 'vt.Root'))
					this.(prop).log = this.log;
				end
			end
			
			% Register vt.Gui as a state listener
			this.registerAllMethodsToState(this.state);
		end
		
		function [] = initializeComponent(this, obj)
			if(isa(obj, 'vt.Root'))
				obj.log = this.log;
			end
			if(isa(obj, 'vt.State.Listener'))
				obj.registerAllMethodsToState(this.state);
			end
			if(isa(obj, 'vt.Action.Dispatcher'))
				this.actionListener.registerAction(obj.action);
			end
		end
		
		function styles = createStyles(~)
			styles = struct( ...
				'Padding', 3, ...
				'Spacing', 3 ...
			);
		end
		
		function gui = createInterface(this)
			% Create the user interface for the application and return a
			% structure of handles for global use.
			gui = struct();
			
			% Open a window
			gui.Window = vt.Component.Window( 'VocalTract ROI Toolbox' );
			
			% + Menu
			gui = this.addMenu(gui);
			
			% Arrange the main interface
			gui.MainLayoutWrapper = vt.Component.Layout.VBoxFlex( ...
				gui.Window, ...
				'Spacing', this.styles.Spacing ...
			);
			gui.MainLayout = vt.Component.Layout.HBoxFlex( ...
				gui.MainLayoutWrapper, ...
				'Spacing', this.styles.Spacing ...
			);
			
			% + Notification bar
			gui = this.addNotificationBar(gui);
			
			% Set the relative sizing between the notification bar and the rest
			% of the interface
			gui.MainLayoutWrapper.setParameters('Heights', [-15, -1]);
			
			% + Image
			gui.LeftBox = vt.Component.Layout.VBox( ...
				gui.MainLayout, ...
				'Padding', this.styles.Padding, ...
				'Spacing', this.styles.Spacing ...
			);
			gui.LeftBoxImageContainer = vt.Component.Container( ...
				gui.LeftBox ...
			);
			
			% + Image controls
			gui = this.addImageControls(gui);
			
			% + Right panels
			gui.RightBox = vt.Component.Layout.TabPanel( ...
				gui.MainLayout, ...
				'TabWidth', 100, ...
				'Padding', this.styles.Padding ...
			);
			gui.RegionSettingsTab = vt.Component.Layout.HBox( ...
				gui.RightBox, ...
				'Padding', this.styles.Padding, ...
				'Spacing', this.styles.Spacing ...
			);
			gui.TimeSeriesTab = vt.Component.Layout.VBox( ...
				gui.RightBox, ...
				'Padding', this.styles.Padding, ...
				'Spacing', this.styles.Spacing ...
			);
			gui.RightBox.setParameters('TabTitles', {'Region settings', 'Timeseries'});
			
			%%% Grid way of doing things
			gui = this.addRegionSettingsGrid(gui);
		end
		
		function gui = addMenu(~, gui)
			% + File menu
			gui.FileMenu = vt.Component.MenuItem( gui.Window,   'File' );
			gui.LoadMenu = vt.Component.MenuItem( gui.FileMenu, 'Load...' );
			gui.ExitMenu = vt.Component.MenuItem.Exit( gui.FileMenu, 'Exit' );
			gui.LoadAvi  = vt.Component.MenuItem.Load( gui.LoadMenu, 'AVI', 'avi' );

			% + Help menu
			gui.HelpMenu = vt.Component.MenuItem( gui.Window, 'Help' );
			gui.DocumentationMenu = vt.Component.MenuItem.Help( gui.HelpMenu, 'Documentation' );
		end
		
		function gui = addNotificationBar(~, gui)
			gui.NotificationBar = vt.Component.Text.NotificationBar( ...
				gui.MainLayoutWrapper ...
			);
			gui.NotificationBarWrapper = vt.Component.Wrapper.NotificationBar( ...
				gui.NotificationBar ...
			);
		end
		
		function gui = addImageControls(this, gui)
			gui.LeftBoxFrameControls = vt.Component.Layout.VBox( ...
				gui.LeftBox ...
			);
			gui.LeftBoxFrameNoControls  = vt.Component.Layout.HBox( ...
				gui.LeftBoxFrameControls ...
				);
			gui.SetCurrentFrameNoControl = vt.Component.TextBox.FrameNo( ...
				gui.LeftBoxFrameNoControls ...
			);
			gui.Slider = vt.Component.Slider.FrameNo( ...
				gui.LeftBoxFrameNoControls ...
			);
			gui.FrameTypeControls = vt.Component.ButtonGroup.FrameType( ...
				gui.LeftBoxFrameControls ...
			);

			% Can this be done when you're creating the object?
			gui.LeftBox.setParameters( 'Heights', [-1, 35], 'Padding', this.styles.Padding );

			gui.Frame = vt.Component.Frame( gui.LeftBoxImageContainer );
			gui.frameContainer = vt.Component.Wrapper.Frame( gui.Frame );
		end
		
		function gui = addRegionSettingsGrid(this, gui)
			gui.RightBoxGrid = vt.Component.Layout.Grid( ...
				gui.RegionSettingsTab, ...
				'Spacing', this.styles.Spacing + 2 ...
			);
			% 1-1 + Region name textbox
			gui.RegionNamePanel = vt.Component.Layout.Panel( ...
				gui.RightBoxGrid, ...
				'Title', 'Region name' ...
			);
			gui.RegionName = vt.Component.TextBox.RegionName( ...
				gui.RegionNamePanel ...
			);
			% 2-1 + Region Shape popup (drop-down) menu
			gui.RegionShapePanel = vt.Component.Layout.Panel( ...
				gui.RightBoxGrid, ...
				'Title', 'Region shape' ...
			);
			gui.RegionShapePopup = vt.Component.Popup.RegionShape( ...
				gui.RegionShapePanel ...
			);
			% 3-1 + Region Type popup (drop-down) menu
			gui.RegionTypePanel = vt.Component.Layout.Panel( ...
				gui.RightBoxGrid, ...
				'Title', 'Region type' ...
			);
			gui.RegionTypePopup = vt.Component.Popup.RegionType( ...
				gui.RegionTypePanel ...
			);
			% 4-1 + Snap to midline checkbox
			gui.SnapToMidlineCheckbox = vt.Component.Checkbox.SnapToMidline( ...
				gui.RightBoxGrid, ...
				'Snap to midline' ...
			);
			% 5-1 + Empty area (for spacing purposes)
			gui.Empty5 = vt.Component.Layout.Empty( ...
				gui.RightBoxGrid ...
			);
			% 6-1 + Change color button
			gui.ChangeColorButton = vt.Component.Button.RegionColor( ...
				gui.RightBoxGrid, ...
				'Change color' ...
			);
			% 7-1 + Show origin checkbox
			gui.ShowOriginCheckbox = vt.Component.Checkbox.ShowOrigin( ...
				gui.RightBoxGrid, ...
				'Show origin' ...
			);
			% 8-1 + Show outline checkbox
			gui.ShowOutlineCheckbox = vt.Component.Checkbox.ShowOutline( ...
				gui.RightBoxGrid, ...
				'Show outline' ...
			);
			% 9-1 + Show fill checkbox
			gui.ShowFillCheckbox = vt.Component.Checkbox.ShowFill( ...
				gui.RightBoxGrid, ...
				'Show fill' ...
			);
			% 1-2 + Radius
			gui.RegionSettings1_2 = vt.Component.Layout.Panel( ...
				gui.RightBoxGrid, ...
				'Title', 'Radius' ...
			);
			gui.RegionRadius = vt.Component.TextBox.Radius( ...
				gui.RegionSettings1_2 ...
			);
			% 2-2 + Empty space
			gui.RegionSettings2_2 = vt.Component.Layout.Empty( ...
				gui.RightBoxGrid ...
			);
			% 3-2 + Empty space
			gui.RegionSettings3_2 = vt.Component.Layout.Empty( ...
				gui.RightBoxGrid ...
			);
			% 4-2 + Allow multiple origins checkbox
			gui.MultipleOriginsCheckbox = vt.Component.Checkbox.MultipleOrigins( ...
				gui.RightBoxGrid, ...
				'Allow multiple origins' ...
			);
			% 5-2 + Empty area (for spacing purposes)
			gui.RegionSettings5_2 = vt.Component.Layout.Empty( ...
				gui.RightBoxGrid ...
			);
			% 6-2 + Save button
			gui.RegionNewButton = vt.Component.Button.NewRegion( ...
				gui.RightBoxGrid, ...
				'New region' ...
			);
			% 7-2 + Save button
			gui.RegionSaveButton = vt.Component.Button.SaveRegion( ...
				gui.RightBoxGrid, ...
				'Save region' ...
			);
			% 8-2 + Delete button
			gui.RegionDeleteButton = vt.Component.Button.DeleteRegion( ...
				gui.RightBoxGrid, ...
				'Delete region' ...
			);
			% 9-2 + Cancel button
			gui.RegionCancelButton = vt.Component.Button.CancelRegion( ...
				gui.RightBoxGrid, ...
				'Cancel region changes' ...
			);
		
% 			gui.RightBoxGrid.handle.Contents
			
			gui.RightBoxGrid.setParameters('Widths', [-1 -1], 'Heights', -1.*ones(1, 9));
		end
		
		function [] = onCurrentRegionChange(this, state)
			% Prevent re-drawing when other changes than shape changes are made
			if(strcmp(this.currentRegion.shape, state.currentRegion.shape))
				return;
			end
			
			% Delete whatever parameter fields are currently present. The calls
			% to delete() are the most important
			% 1. Delete seems to be the only thing that works
			% 2. When vt.State.Listeners are deleted, they first delete their
			%    own listener handles
			delete(this.gui.RightBoxGrid.handle.Contents(10:12));
			switch(this.currentRegion.shape)
				case 'Circle'
					delete(this.gui.RegionRadius);
					this.gui.RegionSettings1_2 = [];
					this.gui.RegionSettings2_2 = [];
					this.gui.RegionSettings3_2 = [];
					this.gui.RegionRadius = [];
					this.gui = rmfield(this.gui, 'RegionSettings1_2');
					this.gui = rmfield(this.gui, 'RegionSettings2_2');
					this.gui = rmfield(this.gui, 'RegionSettings3_2');
					this.gui = rmfield(this.gui, 'RegionRadius');
				case 'Rectangle'
					delete(this.gui.RegionWidth);
					delete(this.gui.RegionHeight);
					this.gui.RegionSettings1_2 = [];
					this.gui.RegionSettings2_2 = [];
					this.gui.RegionSettings3_2 = [];
					this.gui.RegionWidth = [];
					this.gui.RegionHeight = [];
					this.gui = rmfield(this.gui, 'RegionSettings1_2');
					this.gui = rmfield(this.gui, 'RegionSettings2_2');
					this.gui = rmfield(this.gui, 'RegionSettings3_2');
					this.gui = rmfield(this.gui, 'RegionWidth');
					this.gui = rmfield(this.gui, 'RegionHeight');
				case 'Statistically-generated'
					delete(this.gui.MinimumPixels);
					delete(this.gui.SearchRadius);
					delete(this.gui.Tau);
					this.gui.RegionSettings1_2 = [];
					this.gui.RegionSettings2_2 = [];
					this.gui.RegionSettings3_2 = [];
					this.gui.MinimumPixels = [];
					this.gui.SearchRadius = [];
					this.gui.Tau = [];
					this.gui = rmfield(this.gui, 'RegionSettings1_2');
					this.gui = rmfield(this.gui, 'RegionSettings2_2');
					this.gui = rmfield(this.gui, 'RegionSettings3_2');
					this.gui = rmfield(this.gui, 'MinimumPixels');
					this.gui = rmfield(this.gui, 'SearchRadius');
					this.gui = rmfield(this.gui, 'Tau');
				otherwise
					% TODO: something here
			end
			
			switch(state.currentRegion.shape)
				case 'Circle'
					% 1-2 + Radius
					this.gui.RegionSettings1_2 = vt.Component.Layout.Panel( ...
						this.gui.RightBoxGrid, ...
						'Title', 'Radius' ...
					);
					this.gui.RegionRadius = vt.Component.TextBox.Radius( ...
						this.gui.RegionSettings1_2 ...
					);
					this.initializeComponent(this.gui.RegionSettings1_2);
					this.initializeComponent(this.gui.RegionRadius);
					% 2-2 + Empty space
					this.gui.RegionSettings2_2 = vt.Component.Layout.Empty( ...
						this.gui.RightBoxGrid ...
					);
					this.initializeComponent(this.gui.RegionSettings2_2);
					% 3-2 + Empty space
					this.gui.RegionSettings3_2 = vt.Component.Layout.Empty( ...
						this.gui.RightBoxGrid ...
					);
					this.initializeComponent(this.gui.RegionSettings3_2);
				case 'Rectangle'
					% 1-2 + Width
					this.gui.RegionSettings1_2 = vt.Component.Layout.Panel( ...
						this.gui.RightBoxGrid, ...
						'Title', 'Width' ...
					);
					this.gui.RegionWidth = vt.Component.TextBox.Width( ...
						this.gui.RegionSettings1_2 ...
					);
					this.initializeComponent(this.gui.RegionSettings1_2);
					this.initializeComponent(this.gui.RegionWidth);
					% 2-2 + Height
					this.gui.RegionSettings2_2 = vt.Component.Layout.Panel( ...
						this.gui.RightBoxGrid, ...
						'Title', 'Height' ...
					);
					this.gui.RegionHeight = vt.Component.TextBox.Height( ...
						this.gui.RegionSettings2_2 ...
					);
					this.initializeComponent(this.gui.RegionSettings2_2);
					this.initializeComponent(this.gui.RegionHeight);
					% 3-2 + Empty space
					this.gui.RegionSettings3_2 = vt.Component.Layout.Empty( ...
						this.gui.RightBoxGrid ...
					);
					this.initializeComponent(this.gui.RegionSettings3_2);
				case 'Statistically-generated'
					% 1-2 + Minimum # pixels textbox
					this.gui.RegionSettings1_2 = vt.Component.Layout.Panel( ...
						this.gui.RightBoxGrid, ...
						'Title', 'Minimum number of pixels' ...
					);
					this.gui.MinimumPixels = vt.Component.TextBox.MinimumPixels( ...
						this.gui.RegionSettings1_2 ...
					);
					this.initializeComponent(this.gui.RegionSettings1_2);
					this.initializeComponent(this.gui.MinimumPixels);
					% 2-2 + Search radius textbox
					this.gui.RegionSettings2_2 = vt.Component.Layout.Panel( ...
						this.gui.RightBoxGrid, ...
						'Title', 'Search radius' ...
					);
					this.gui.SearchRadius = vt.Component.TextBox.SearchRadius( ...
						this.gui.RegionSettings2_2 ...
					);
					this.initializeComponent(this.gui.RegionSettings2_2);
					this.initializeComponent(this.gui.SearchRadius);
					% 3-2 + Tau textbox
					this.gui.RegionSettings3_2 = vt.Component.Layout.Panel( ...
						this.gui.RightBoxGrid, ...
						'Title', 'Tau' ...
					);
					this.gui.Tau = vt.Component.TextBox.Tau( ...
						this.gui.RegionSettings3_2 ...
					);
					this.initializeComponent(this.gui.RegionSettings3_2);
					this.initializeComponent(this.gui.Tau);
				otherwise
					% TODO: add the rest
			end
			
			% re-order the elements so that elements 16:18 are 10:12
			newOrder = [1:9 16:18 10:15];
			this.gui.RightBoxGrid.handle.Contents = this.gui.RightBoxGrid.handle.Contents(newOrder);
			
			% Update the local copy of currentRegion
			this.currentRegion = state.currentRegion;
		end
	end
end